apiVersion: v1
kind: ServiceAccount
metadata:
  name: restarter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: restarter-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restarter_admin_dev
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restarter-role
subjects:
- kind: ServiceAccount
  name: restarter
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: restarter
  namespace: default
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: restarter
          containers:
          - name: restarter
            image: anilkuscu95/restarter
            command: ["/scripts/entrypoint.sh"]
            args: ["nginx"]
            imagePullPolicy: IfNotPresent
#            env:
#            - name: DEBUG
#              value: "on"
          restartPolicy: OnFailure
